config/routes.rb
Rails.application.routes.draw do
  mount Flipper::UI.app(FlipperDemo.flipper) => '/flipper'

  devise_for :users
  resources :lists do
    resources :items, shallow: true
    resources :imports, only: [:new, :create]
  end

  root to: "lists#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/flippable.rb
module Flippable
  extend ActiveSupport::Concern

  included do
    def flipper_id
      "#{self.class.name}:#{id}"
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  include Flippable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_list

  # GET /imports/new
  def new
  end

  # POST /imports
  # POST /imports.json
  def create
    ImportJob.perform_now(@list, import_params.tempfile.path)
    redirect_to @list, notice: 'Import was successfully created.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = current_user.lists.find(params[:list_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def import_params
      params.require(:file)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_list, only: [:index, :new, :create]

  # GET /lists/1/items.json
  def index
    @items = @list.items
  end

  # GET /items/1
  # GET /items/1.json
  def show
    render :edit
  end

  # GET /lists/1/items/new
  def new
    @item = @list.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /lists/1/items
  # POST /lists/1/items.json
  def create
    @item = @list.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @list, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item.list, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @item.list, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.where(list_id: current_user.list_ids).find(params[:id])
    end

    def set_list
      @list = current_user.lists.find(params[:list_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :notes, :due_at)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = current_user.lists.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = current_user.lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/imports/_form.html.erb
<%= form_tag({ controller: 'imports', action: 'create', list: list }, multipart: true) do %>
  <div class="field">
    <%= label_tag :file, "File" %>
    <%= file_field_tag :file, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= submit_tag "Import", class: ['btn', 'btn-primary'] %>
  </div>
<% end %>

app/views/imports/new.html.erb
<h1>New Import</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', @list %>

app/views/items/_form.html.erb
<%= form_for([list, item]) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :due_at %>
    <%= f.text_field :due_at, 'data-provide' => 'datepicker', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Update Item", class: ['btn', 'btn-primary'] %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', list: @list, item: @item %>

<%= link_to 'Back', @item.list %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', list: @list, item: @item %>

<%= link_to 'Back', list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Update List", class: ['btn', 'btn-primary'] %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', @list %>

app/views/lists/index.html.erb
<h1>To Do Lists</h1>

<table class="table table-striped">
  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= link_to list.title, list %></td>
        <td class="right-align"><%= link_to '', list, method: :delete, data: { confirm: 'Are you sure?' }, class: ['glyphicon', 'glyphicon-trash'], title: 'Destroy' %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2"><%= link_to '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New List'.html_safe, new_list_path %></td>
    </tr>
  </tfoot>
</table>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.title %>
  <small>
    <%= link_to '', edit_list_path(@list), class: ['glyphicon', 'glyphicon-pencil'] %>
    <%= link_to '', new_list_import_path(@list), class: ['glyphicon', 'glyphicon glyphicon-import'] %>
  </small>
</h1>

<%= @list.description %>

<h2>Items</h2>

<table class="table table-striped">
  <tbody>
    <% @list.items.each do |item| %>
      <tr>
        <td><%= link_to item.title, item %></td>
        <td class="right-align">
          <%= link_to '', item, method: :delete, data: { confirm: 'Are you sure?' }, class: ['glyphicon', 'glyphicon-trash'], title: 'Destroy' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2"><%= link_to '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Item'.html_safe, new_list_item_path(@list) %></td>
    </tr>
  </tfoot>
</table>

<%= link_to 'Back', lists_path %>